apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-initdb"
  labels:
    {{- include "maian-music.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "maian-music.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: "{{ .Chart.Name }}-wait-for-db"
        image: "groundnuty/k8s-wait-for:1.3"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: 
        - "pod"
        - "-lapp.kubernetes.io/component=mysql"
      containers:
      - name: {{ .Chart.Name }}-initdb
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: "/initdb.sh"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: MM_DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: MM_DB_PASS
          - name: MM_DB_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: MM_DB_USER
          - name: MM_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: MM_DB_HOST
          - name: MM_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: MM_DB_NAME
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.initdb.restartPolicy }}
